import {test} from 'node:test';
import assert from 'node:assert/strict';
import {MockTransport} from '../src/api/mock.ts';
import {InboxRepository} from '../src/api/repository.ts';
import {demoAccounts} from '../src/api/fixtures.ts';
import {ApiError,messageKey,type Message,type Page,type Conversation} from '../src/api/types.ts';
import type {Storage} from '../src/storage/interface.ts';
class Memory implements Storage {
 data=new Map<string,string>();async get<T>(k:string):Promise<T|null>{const v=this.data.get(k);return v?JSON.parse(v):null}async put(k:string,v:unknown){this.data.set(k,JSON.stringify(v))}async remove(k:string){this.data.delete(k)}async scan<T>(p:string):Promise<T[]>{return [...this.data].filter(([k])=>k.startsWith(p)).map(([,v])=>JSON.parse(v))}async clear(){this.data.clear()}async close(){}
}
function context(i=0){const disk=new Memory();const api=new MockTransport(demoAccounts[i],disk);api.latency=0;return {disk,api,repo:new InboxRepository(disk,api)}}
test('initial list stays bounded, continuation survives restart and a failed page preserves cached data',async()=>{const disk=new Memory();let fail=false;const calls:number[]=[];const api={request:async<T>(request:any)=>{const start=Number(request.query.cursor||0);calls.push(start);if(fail&&start===200)throw new ApiError(0,'network_error','offline');return {items:Array.from({length:Math.min(50,228-start)},(_,i)=>({id:start+i+1,kind:'comments',last_message_at:'2026-10-05T00:00:00Z'})),next_cursor:start+50<228?String(start+50):null,complete:start+50>=228} as T}};const first=new InboxRepository(disk,api);assert.equal((await first.list()).length,200);assert.equal(await disk.get('sync:list-complete'),false);assert.equal(await disk.get('sync:list-cursor'),'200');const reopened=new InboxRepository(disk,api);fail=true;await assert.rejects(reopened.more());assert.equal((await reopened.cachedList()).length,200);assert.equal(await disk.get('sync:list-cursor'),'200');fail=false;assert.equal((await reopened.more()).length,228);assert.equal(await disk.get('sync:list-complete'),true);assert.equal(await disk.get('sync:list-cursor'),null);calls.length=0;assert.equal((await reopened.list()).length,228);assert.deepEqual(calls,[0,50,100,150,200])});
test('existing Inbox pagination and kind+id timeline identities survive cache/restart',async()=>{const {disk,repo}=context();await repo.list();const first=await repo.history(1);assert.equal(first.items.length,40);assert.ok(first.next_cursor);const second=await repo.history(1,first.next_cursor!);assert.equal(second.next_cursor,null);const cached=await repo.cachedMessages(1);assert.equal(cached.length,68);assert.equal(new Set(cached.map(messageKey)).size,68);await disk.put('draft:1:reply','Rascunho persistente');const reopened=new InboxRepository(disk,repo.api);assert.equal(await reopened.drafts(1,'reply'),'Rascunho persistente');assert.equal((await reopened.cachedMessages(1)).length,68)});
test('reply request_id is idempotent, including uncertain-result reconciliation',async()=>{const {api,disk,repo}=context();await repo.list();await repo.history(1);api.uncertainNext=true;const entry={request_id:'test-request-0001',conversationId:1,body:'Mensagem única',mode:'reply' as const,timestamp:new Date().toISOString(),status:'sending' as const};await assert.rejects(repo.send(entry),(e:any)=>e.code==='uncertain');assert.equal((await disk.scan('outbox:')).length,1);await repo.poll(1);assert.equal((await disk.scan('outbox:')).length,0);await repo.send(entry);assert.equal((await repo.cachedMessages(1)).filter(m=>m.body==='Mensagem única').length,1)});
test('version conflict and closed WhatsApp window are real mock failures',async()=>{const {api,repo}=context();await repo.list();await assert.rejects(repo.transition(1,0,'take'),(e:any)=>e.status===409);await api.closeWindow(1);await assert.rejects(api.request({method:'POST',path:'/inbox/api/conversations/1/reply',body:{body:'Livre',request_id:'window-test-001'}}),(e:any)=>e.code==='window_closed');await assert.rejects(api.request({method:'POST',path:'/inbox/api/conversations/1/reply',body:{body:'Template',request_id:'window-test-002',template_id:101,variables:{}}}),(e:any)=>e.code==='variables');const accepted=await api.request<any>({method:'POST',path:'/inbox/api/conversations/1/reply',body:{body:'Template',request_id:'window-test-003',template_id:101,variables:{'BODY:1':'Marina','BODY:2':'relatório'}}});assert.equal(accepted.status,'pending');const detail=await api.request<Conversation>({method:'GET',path:'/inbox/api/conversations/1'});assert.equal(detail.mobile.window_open,false)});
test('account caches and remote mocks cannot cross origin/user boundaries',async()=>{const a=context(0),b=context(1);await a.repo.list();await b.repo.list();await a.repo.disk.put('draft:1:reply','Só Macro');assert.equal(await b.repo.drafts(1,'reply'),'');assert.equal((await b.repo.cachedList())[0].contact_name,'Beatriz Lima');await a.repo.disk.clear();assert.equal((await b.repo.cachedList()).length,7)});
test('offline preserves cache and prevents mutation; sending at restart becomes uncertain',async()=>{const {api,disk,repo}=context();await repo.list();api.offline=true;await assert.rejects(repo.list(),(e:any)=>e.code==='offline');assert.equal((await repo.cachedList()).length,7);await disk.put('outbox:restarted',{request_id:'restarted',conversationId:1,body:'Pendente',mode:'reply',timestamp:new Date().toISOString(),status:'sending'});await repo.recover();assert.equal((await disk.get<any>('outbox:restarted')).status,'uncertain')});

test('comment kind filter, public/private replies and linked conversation remain separate',async()=>{const {api}=context();const comments=await api.request<Page<Conversation>>({method:'GET',path:'/inbox/api/conversations',query:{kind:'comments'}});assert.equal(comments.items.length,3);assert.deepEqual(new Set(comments.items.map(c=>c.channel)),new Set(['instagram','facebook']));await api.request({method:'POST',path:'/inbox/api/conversations/5/reply',body:{body:'Retorno privado',request_id:'private-reply-0001',reply_mode:'private'}});const comment=await api.request<Page<Message>>({method:'GET',path:'/inbox/api/conversations/5/history'});const privateChat=await api.request<Page<Message>>({method:'GET',path:'/inbox/api/conversations/2/history'});assert.equal(comment.items.find(m=>m.body==='Retorno privado')?.replyMode,'private');assert.equal(privateChat.items.filter(m=>m.body==='Retorno privado').length,1);await assert.rejects(api.request({method:'POST',path:'/inbox/api/conversations/7/reply',body:{body:'Privado',request_id:'private-unavailable',reply_mode:'private'}}),(e:any)=>e.code==='private_unavailable')});
test('spam moderation persists, is reversible, versioned, and blocks sends without deleting history',async()=>{const {api,disk}=context();await api.request({method:'POST',path:'/inbox/mobile/conversations/7/moderation',body:{version:1,action:'spam'}});let c=await api.request<Conversation>({method:'GET',path:'/inbox/api/conversations/7'});assert.equal(c.moderation?.spam,true);await assert.rejects(api.request({method:'POST',path:'/inbox/api/conversations/7/reply',body:{body:'Não enviar',request_id:'spam-send-0001'}}),(e:any)=>e.code==='spam');await assert.rejects(api.request({method:'POST',path:'/inbox/mobile/conversations/7/moderation',body:{version:1,action:'restore'}}),(e:any)=>e.status===409);const reopened=new MockTransport(demoAccounts[0],disk);reopened.latency=0;c=await reopened.request({method:'POST',path:'/inbox/mobile/conversations/7/moderation',body:{version:c.version,action:'restore'}});assert.equal(c.moderation?.spam,false);const history=await reopened.request<Page<Message>>({method:'GET',path:'/inbox/api/conversations/7/history'});assert.ok(history.items.some(m=>m.kind==='comment'));assert.ok(history.items.some(m=>m.body==='Removido do spam'))});
test('blocked author suppresses new-message unread count and cannot cross account storage',async()=>{const a=context(),b=context(1);await a.repo.list();await b.repo.list();const blocked=await a.api.request<Conversation>({method:'POST',path:'/inbox/mobile/conversations/7/moderation',body:{version:1,action:'block'}});await a.api.inject(7,'Outro spam');const after=await a.api.request<Conversation>({method:'GET',path:'/inbox/api/conversations/7'});assert.equal(after.unread,blocked.unread);assert.equal(after.moderation?.blockedAuthor,true);const assistant=await a.api.request<any>({method:'POST',path:'/inbox/mobile/assistant/messages',body:{message:'Quem está aguardando resposta?'}});assert.equal(assistant.text.includes('Perfil suspeito'),false);const other=await b.api.request<Conversation>({method:'GET',path:'/inbox/api/conversations/7'});assert.equal(other.moderation?.blockedAuthor,false)});
test('transfer blocks reply by previous operator; snooze wakes on new incoming message',async()=>{const {repo,api}=context();await repo.list();const c=await repo.transition(1,1,'transfer',{target_user_id:42});await assert.rejects(api.request({method:'POST',path:'/inbox/api/conversations/1/reply',body:{body:'Resposta antiga',request_id:'transferred-reply'}}),(e:any)=>e.code==='assigned');const delayed=await repo.transition(1,c.version,'snooze',{until:new Date(Date.now()+60000).toISOString()});assert.equal(delayed.lifecycle,'snoozed');await api.inject(1);const awake=await api.request<Conversation>({method:'GET',path:'/inbox/api/conversations/1'});assert.equal(awake.lifecycle,'open');assert.equal(awake.snoozed_until,null);assert.equal(awake.assignee?.id,42)});
test('agent handoff pauses on human takeover and CRM conflict never overwrites another contact',async()=>{const {repo,api}=context();await repo.list();const assigned=await api.request<Conversation>({method:'POST',path:'/inbox/api/conversations/3/ai',body:{version:1,action:'assign',key:'triagem'}});assert.equal(assigned.mobile.ai,true);const human=await repo.transition(3,assigned.version,'take');assert.equal(human.agent?.status,'paused');assert.equal(human.human_takeover,true);await assert.rejects(api.request({method:'POST',path:'/inbox/api/conversations/1/email-actions',body:{version:1,email:'contato1@example.com'}}),(e:any)=>e.code==='contact_conflict');const changed=await api.request<Conversation>({method:'POST',path:'/inbox/api/conversations/1/email-actions',body:{version:1,email:'marina-new@example.com',campaign_id:2,segment_id:1}});assert.equal(changed.contact?.email,'marina-new@example.com');assert.equal(changed.origins.campaign,'Relatório da rodada');assert.ok(changed.campaigns?.includes('Boas-vindas'));assert.ok(changed.segments?.includes('Interessados em futebol'))});

test('latest list membership prevents stale cached conversations from returning after a message write',async()=>{const {disk,api,repo}=context();const all=await repo.list();const current=all.slice(0,2);const filtered=new InboxRepository(disk,{request:async<T>()=>({items:current,next_cursor:null,complete:true} as T)});await filtered.list();await repo.saveConversations([all[3]]);assert.deepEqual((await filtered.cachedList()).map(c=>c.id),current.map(c=>c.id));assert.equal((await disk.scan('conversation:')).length,2)});
test('partial lists stay marked partial without deleting older history or drafts',async()=>{const {disk,repo}=context();await repo.list();await repo.history(1);await disk.put('draft:1:reply','Preservar');const filtered=new InboxRepository(disk,{request:async<T>()=>({items:[],next_cursor:null,complete:false} as T)});await filtered.list();assert.equal(await disk.get('sync:list-complete'),false);assert.equal((await filtered.cachedList()).length,0);assert.equal((await filtered.cachedMessages(1)).length,40);assert.equal(await filtered.drafts(1,'reply'),'Preservar')});
test('refresh catches messages arriving across multiple pages and updates remote receipts',async()=>{const disk=new Memory();await disk.put('message:1:outbound:1',{kind:'outbound',id:1,body:'Mensagem existente',timestamp:'2026-10-04T20:00:00Z',status:'sent'});let calls=0;const repo=new InboxRepository(disk,{request:async<T>()=>{calls++;return (calls===1?{items:[{kind:'message',id:3,body:'Nova',timestamp:'2026-10-04T20:02:00Z'}],next_cursor:'older'}:{items:[{kind:'message',id:2,body:'Intermediária',timestamp:'2026-10-04T20:01:00Z'},{kind:'outbound',id:1,body:'Mensagem existente',timestamp:'2026-10-04T20:00:00Z',status:'read'}],next_cursor:null}) as T}});const messages=await repo.refreshHistory(1);assert.equal(calls,2);assert.equal(messages.length,3);assert.equal(messages[0].status,'read')});
