import test from 'node:test';import assert from 'node:assert/strict';
import {magicRequest,magicVerify} from '../src/api/magic-code.ts';import {discover,type MobileConfig} from '../src/api/http.ts';
const config:MobileConfig={version:1,name:'Example',origin:'https://example.com',api_base:'https://example.com/inbox/mobile/api',authorization_endpoint:'https://example.com/s/inbox/mobile/authorize',token_endpoint:'https://example.com/inbox/mobile/token',magic_code_endpoint:'https://example.com/inbox/mobile/magic-code',redirect_uri:'mautic-inbox-demo://oauth/callback',capabilities:{magic_code_login:true}};
const proof={verifier:'a'.repeat(64),challenge:'b'.repeat(43)};const id='c'.repeat(64);
test('magic code request normalizes email, binds proof and honors server deadlines',async()=>{let body:any;const before=Date.now();const pending=await magicRequest(config,' ME@Example.com ',proof,(async(url,options)=>{assert.equal(url,config.magic_code_endpoint);assert.equal(options?.redirect,'error');body=JSON.parse(String(options?.body));return Response.json({request_id:id,expires_in:300,resend_after:60},{status:202})}) as typeof fetch);assert.deepEqual(body,{email:'me@example.com',code_challenge:proof.challenge});assert.equal(pending.verifier,proof.verifier);assert.ok(pending.expiresAt>=before+300000);assert.ok(pending.resendAt>=before+60000)});
test('magic verify uses only this request and PKCE and returns actual user',async()=>{const p={id,...proof,email:'me@example.com',expiresAt:Date.now()+300000,resendAt:0};const login=await magicVerify(config,p,'123456',(async(url,options)=>{assert.equal(url,config.token_endpoint);assert.deepEqual(JSON.parse(String(options?.body)),{grant_type:'email_code',request_id:id,code:'123456',code_verifier:proof.verifier});return Response.json({access_token:'access',refresh_token:'refresh',expires_in:3600,user:{id:7,name:'Operator',email:'me@example.com'}})}) as typeof fetch);assert.equal(login.user.id,7);assert.equal(login.session.refreshToken,'refresh')});
test('expired, incomplete and unsupported codes make no network request',async()=>{let calls=0;const fetcher=(async()=>{calls++;return Response.json({})}) as typeof fetch;const p={id,...proof,email:'me@example.com',expiresAt:0,resendAt:0};await assert.rejects(magicVerify(config,p,'123456',fetcher),/expirado/);await assert.rejects(magicVerify(config,{...p,expiresAt:Date.now()+300000},'123',fetcher),/seis dígitos/);await assert.rejects(magicRequest({...config,capabilities:{}},p.email,proof,fetcher),/não oferece/);assert.equal(calls,0)});
test('failed code and cooldown expose actionable errors without granting a session',async()=>{const p={id,...proof,email:'me@example.com',expiresAt:Date.now()+300000,resendAt:0};await assert.rejects(magicVerify(config,p,'123456',(async()=>Response.json({error:'invalid_grant'},{status:400})) as typeof fetch),/inválido ou expirado/);await assert.rejects(magicRequest(config,p.email,proof,(async()=>Response.json({error:'rate_limited'},{status:429})) as typeof fetch),/Aguarde um minuto/)});
test('discovery rejects a foreign magic code destination',async()=>{const original=globalThis.fetch;globalThis.fetch=(async()=>Response.json({...config,magic_code_endpoint:'https://foreign.example/magic'})) as typeof fetch;try{await assert.rejects(discover(config.origin),/destino diferente/)}finally{globalThis.fetch=original}});
