import {t} from '../i18n/engine';
import React,{useEffect,useRef,useState} from 'react';
import {View,ScrollView} from 'react-native';
import {useApp} from '../store/app';
import {useTheme} from '../theme';
import {T,Tap,Icon,Button,Field,Card,Header,Top,DetailRow} from './ui';
import {Sheet} from './Sheet';
import {CrmAutocomplete} from './CrmAutocomplete';
import type {CrmOption} from './crm-catalogue';
import type {Conversation,Page} from '../api/types';
type ContactCard={id:number;name:string;email:string;phone:string};
type ChannelOption={key:string;state_id:number|null;asset_id:number;channel:string;name:string;available:boolean;reason:string|null};
type ContactDetail=ContactCard&{campaigns:{id:number;name:string}[];channels:ChannelOption[]};

export function StartContactConversation({contactId}:{contactId:number}){
 const s=useApp();const c=useTheme();const [open,setOpen]=useState(false);const [detail,setDetail]=useState<ContactDetail|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const request=useRef(0);
 useEffect(()=>{request.current++;setOpen(false);setDetail(null);setError('')},[s.active?.id,contactId]);
 async function load(){if(!s.repo)return;const seq=++request.current;setOpen(true);setBusy(true);setError('');try{const saved=await s.repo.disk.get<ContactDetail>('contact:'+contactId);if(seq!==request.current)return;if(saved)setDetail(saved);if(s.offline){if(!saved)setError(t("contact.channelsOffline"));return}const data=await s.repo.api.request<ContactDetail>({method:'GET',path:`/inbox/mobile/contacts/${contactId}`});await s.repo.disk.put('contact:'+contactId,data);if(seq===request.current)setDetail(data)}catch(e){if(seq===request.current)setError(e instanceof Error?e.message:String(e))}finally{if(seq===request.current)setBusy(false)}}
 async function start(option:ChannelOption){if(!s.repo||s.offline||busy)return;const seq=++request.current;setBusy(true);setError('');try{let id=option.state_id;if(!id){const fresh=await s.repo.api.request<Conversation>({method:'POST',path:`/inbox/mobile/contacts/${contactId}/start`,body:{channel_key:option.key}});await s.repo.saveConversations([fresh]);id=fresh.id;}if(seq!==request.current||useApp.getState().active?.id!==s.active?.id)return;setOpen(false);await s.openChat(id)}catch(e){if(seq===request.current)setError(e instanceof Error?e.message:String(e))}finally{if(seq===request.current)setBusy(false)}}
 return <><Button label={t("contact.start")} testID="start-contact-conversation" disabled={s.offline} onPress={()=>void load()}/><Sheet title={t("contact.startTitle")} visible={open} onClose={()=>{request.current++;setOpen(false);setBusy(false)}}><T bold size={14}>{detail?.name||t("contact.loading")}</T><T size={12} muted>{t("contact.chooseChannel")}</T>{detail?.channels.map(option=><View key={option.key} style={{gap:4}}><Button quiet label={t(option.state_id?'contact.openChannel':'contact.startChannel',{name:option.name})} disabled={busy||s.offline||(!option.state_id&&!option.available)} testID={'start-'+option.key} onPress={()=>void start(option)}/>{option.reason&&<T size={11} color={c.soft}>{option.reason}</T>}</View>)}{detail&&!detail.channels.length&&<T size={12} muted>{t("contact.noChannels")}</T>}{busy&&<T muted size={12}>{t("contact.loadingMautic")}</T>}{error&&<T color={c.warn} size={12} accessibilityRole="alert">{error}</T>}</Sheet></>;
}

function DirectoryContact({contact,onBack}:{contact:ContactCard;onBack:()=>void}){
 const s=useApp();const c=useTheme();const [detail,setDetail]=useState<ContactDetail|null>(null);const [error,setError]=useState('');
 useEffect(()=>{let current=true;setDetail(null);setError('');const repo=s.repo;if(repo)void(async()=>{const cached=await repo.disk.get<ContactDetail>('contact:'+contact.id);if(current&&cached)setDetail(cached);if(s.offline)return;try{const fresh=await repo.api.request<ContactDetail>({method:'GET',path:`/inbox/mobile/contacts/${contact.id}`});await repo.disk.put('contact:'+contact.id,fresh);if(current)setDetail(fresh)}catch(e){if(current)setError(e instanceof Error?e.message:String(e))}})().catch(e=>{if(current)setError(String(e))});return()=>{current=false}},[s.active?.id,contact.id,s.offline]);
 return <View style={{flex:1}}><Header title={t("contact.title")} onBack={onBack}/><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={{padding:18,gap:14}}><T size={24} bold>{detail?.name||contact.name}</T><Card><DetailRow label="E-mail" value={detail?.email||contact.email||t("contact.notProvided")}/><DetailRow label={t("contact.phone")} value={detail?.phone||contact.phone||t("contact.notProvided")}/></Card><Card><T bold size={14}>{t("contact.campaigns")}</T>{detail?.campaigns.map(campaign=><T key={campaign.id} size={12}>{campaign.name}</T>)}{detail&&!detail.campaigns.length&&<T size={12} muted>{t("contact.noMembership")}</T>}</Card><StartContactConversation contactId={contact.id}/>{error&&<T size={12} color={c.warn} accessibilityRole="alert">{error}</T>}<T size={11} muted>{s.offline?t("contact.cachedData"):t("contact.realCrm")}</T></ScrollView></View>;
}

export function ContactDirectory(){
 const s=useApp();const c=useTheme();const [search,setSearch]=useState('');const [segment,setSegment]=useState(0);const [segmentOption,setSegmentOption]=useState<CrmOption|null>(null);const [campaign,setCampaign]=useState(0);const [campaignOption,setCampaignOption]=useState<CrmOption|null>(null);const [expanded,setExpanded]=useState<'segment'|'campaign'|null>(null);const [items,setItems]=useState<ContactCard[]>([]);const [cursor,setCursor]=useState<string|null>(null);const [loading,setLoading]=useState(false);const [error,setError]=useState('');const [selected,setSelected]=useState<ContactCard|null>(null);const seq=useRef(0);
 useEffect(()=>{seq.current++;setSelected(null);setItems([]);setSearch('');setCampaign(0);setCampaignOption(null);setSegment(0);setSegmentOption(null);setExpanded(null)},[s.active?.id]);
 async function load(more=false){const repo=s.repo;if(!repo)return;const generation=++seq.current;const account=s.active?.id;const next=more?cursor:null;const key='contacts:list:'+JSON.stringify([search,segment,campaign,next]);const valid=()=>generation===seq.current&&useApp.getState().active?.id===account;setLoading(true);setError('');try{const cached=await repo.disk.get<Page<ContactCard>>(key);if(cached&&valid()){setItems(old=>more?[...old,...cached.items.filter(item=>!old.some(x=>x.id===item.id))]:cached.items);setCursor(cached.next_cursor)}if(s.offline){if(!cached&&valid()){setItems([]);setCursor(null);setError(t("contact.searchOffline"))}return}const fresh=await repo.api.request<Page<ContactCard>>({method:'GET',path:'/inbox/mobile/contacts',query:{search,segment_id:segment,campaign_id:campaign,limit:30,...(next?{cursor:next}:{})}});await repo.disk.put(key,fresh);if(valid()){setItems(old=>more?[...old,...fresh.items.filter(item=>!old.some(x=>x.id===item.id))]:fresh.items);setCursor(fresh.next_cursor)}}catch(e){if(valid())setError(e instanceof Error?e.message:String(e))}finally{if(valid())setLoading(false)}}
 useEffect(()=>{seq.current++;setItems([]);setCursor(null);const timer=setTimeout(()=>void load(),250);return()=>{clearTimeout(timer);seq.current++}},[s.active?.id,search,segment,campaign,s.offline]);
 if(selected)return <DirectoryContact contact={selected} onBack={()=>setSelected(null)}/>;
 return <View style={{flex:1}}><Top/><ScrollView keyboardShouldPersistTaps="handled" keyboardDismissMode="on-drag" contentContainerStyle={{padding:18,gap:12}}><T bold size={27} style={{lineHeight:35,letterSpacing:-.8}}>{t("nav.contacts")}</T><T muted size={13}>{t("contact.crmHint")}</T><Field label={t("contact.search")} testID="search-crm-contact" value={search} onChange={setSearch} placeholder={t("contact.searchPlaceholder")}/><CrmAutocomplete kind="segment" label={t("contact.segmentFilter")} value={segmentOption} onChange={option=>{setSegmentOption(option);setSegment(option?.id||0)}} expanded={expanded==='segment'} onExpandedChange={open=>setExpanded(open?'segment':null)} emptyLabel={t("contact.allSegments")}/><CrmAutocomplete kind="campaign" label={t("contact.campaignFilter")} value={campaignOption} onChange={option=>{setCampaignOption(option);setCampaign(option?.id||0)}} expanded={expanded==='campaign'} onExpandedChange={open=>setExpanded(open?'campaign':null)} emptyLabel={t("contact.allCampaigns")}/>{items.map(contact=><Tap key={contact.id} testID={'crm-contact-'+contact.id} label={t("contact.title")+" "+contact.name} onPress={()=>setSelected(contact)}><Card style={{flexDirection:'row',alignItems:'center',gap:12}}><View style={{flex:1}}><T bold>{contact.name}</T><T size={12} muted>{contact.email||contact.phone}</T></View><Icon name="chevron-forward" color={c.faint}/></Card></Tap>)}{loading&&<T size={12} muted>{t("contact.loadingContacts")}</T>}{!items.length&&!loading&&!error&&<T size={12} muted>{t("contact.emptySearch")}</T>}{cursor&&<Button quiet label={t("contact.loadMore")} disabled={loading||s.offline} onPress={()=>void load(true)}/>} {error&&<T size={12} color={c.warn} accessibilityRole="alert">{error}</T>}{s.offline&&<T size={11} muted>{t("contact.offline")}</T>}</ScrollView></View>;
}
