import {t} from '../i18n/engine.ts';
import React,{useState,useEffect} from 'react';
import {View,ScrollView} from 'react-native';
import {useApp} from '../store/app';
import {useTheme} from '../theme';
import {type CannedResponse} from '../api/types';
import {T,Tap,Button,Field,Card} from './ui';
import {Sheet} from './Sheet';
import {CrmAutocomplete} from './CrmAutocomplete';
import type {CrmOption,CatalogueKind} from './crm-catalogue';
export type Panel='transfer'|'snooze'|'canned'|'agent'|'moderation'|'crm'|null;
const titles={transfer:"actions.transfer",snooze:"actions.snooze",canned:"actions.canned",agent:"actions.agent",moderation:"actions.moderate",crm:"actions.crm"} as const;
export function ConversationActions({panel,onClose,email=''}:{panel:Panel;onClose:()=>void;email?:string}){
 const s=useApp();const c=useTheme();const [canned,setCanned]=useState<CannedResponse[]>([]);const [loading,setLoading]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [confirm,setConfirm]=useState('');const [duration,setDuration]=useState(60);const [address,setAddress]=useState(email);const [campaign,setCampaign]=useState<CrmOption|null>(null);const [segment,setSegment]=useState<CrmOption|null>(null);const [catalogue,setCatalogue]=useState<CatalogueKind|null>(null);const [review,setReview]=useState(false);const [users,setUsers]=useState<{id:number;name:string}[]>([]);const [agents,setAgents]=useState<{key:string;name:string;allowed?:boolean;reason_label?:string}[]>([]);const [crm,setCrm]=useState<{campaigns:{id:number;name:string}[];segments:{id:number;name:string}[];matches?:{id:number;name:string;email:string}[];contact?:{id:number;name:string};can_edit?:boolean}>({campaigns:[],segments:[]});const [contactId,setContactId]=useState(0);const [create,setCreate]=useState(false);const [name,setName]=useState('');const [body,setBody]=useState('');
 const conversation=s.conversations.find(x=>x.id===s.conversationId);
 useEffect(()=>{let active=true;setError('');setConfirm('');setReview(false);setCreate(false);setBusy(false);setAddress(email||conversation?.contact?.email||'');setCampaign(null);setSegment(null);setCatalogue(null);setContactId(conversation?.contact?.id||0);setUsers([]);setAgents([]);setCanned([]);setLoading(panel==='canned');setName('');setBody('');setCrm({campaigns:[],segments:[]});
  if((panel==='transfer'||panel==='agent')&&s.repo&&!s.offline){void s.repo.api.request<any>({method:'GET',path:panel==='agent'&&s.active?.mode==='live'?`/inbox/api/conversations/${s.conversationId}/ai`:'/inbox/mobile/operator-options'}).then(data=>{if(active){setUsers(data.users||[]);setAgents(data.agents||[])}}).catch(e=>{if(active)setError(String(e))})}
  if(panel==='crm'&&s.repo&&!s.offline){void s.repo.api.request<any>({method:'GET',path:`/inbox/api/conversations/${s.conversationId}/email-options`,query:{email:email||conversation?.contact?.email||'',include_catalog:0}}).then(data=>{if(active)setCrm(data)}).catch(e=>{if(active)setError(String(e))})}
  if(panel==='canned'&&s.repo){const repo=s.repo;void (async()=>{const cache=await repo.disk.get<CannedResponse[]>('feature:canned');if(active&&cache)setCanned(cache);if(s.offline){if(active)setLoading(false);return}try{const result=await repo.api.request<{items:CannedResponse[]}>({method:'GET',path:'/inbox/mobile/canned-responses'});await repo.disk.put('feature:canned',result.items);if(active)setCanned(result.items)}catch(e){if(active)setError(String(e))}finally{if(active)setLoading(false)}})().catch(e=>{if(active){setError(String(e));setLoading(false)}});}
  return()=>{active=false};
 },[panel,s.active?.id,s.conversationId,email]);
 if(!conversation||!panel)return null;
 async function run(job:()=>Promise<unknown>){if(busy)return;setBusy(true);setError('');try{const result=await job();if(result!==false)onClose();else setError(useApp.getState().toast||t("actions.saveFailed"))}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 const option=(label:string,selected:boolean,onPress:()=>void,testID?:string)=><Tap key={label} label={label} testID={testID} onPress={onPress} style={{minHeight:36,paddingHorizontal:10,paddingVertical:6,borderRadius:9,borderWidth:1,borderColor:selected?c.blue:c.line,backgroundColor:selected?c.tint:c.paper}}><T size={11} bold={selected} color={selected?c.blue:c.soft}>{label}</T></Tap>;
 const warning=confirm==='block'?t("actions.blockWarning"):confirm==='hide'?(s.active?.mode==='mock'?t("actions.hideMockWarning"):t("actions.hideWarning")):confirm==='spam'?t("actions.spamWarning"):(s.active?.mode==='mock'?t("actions.recordMockWarning"):t("actions.recordWarning"));
 return <Sheet title={t(titles[panel])} visible onClose={onClose}><T size={11} muted>{conversation.contact_name} · {s.active?.name}</T>
 {panel==='transfer'&&<><T size={12} muted>{t("actions.chooseOperator")}</T>{users.map(user=><Button key={user.id} quiet label={user.name} disabled={busy||s.offline} testID={'transfer-'+user.id} onPress={()=>void run(()=>s.transition('transfer',{target_user_id:user.id}))}/>)}<Button quiet label={t("actions.returnQueue")} disabled={busy||s.offline} onPress={()=>void run(()=>s.transition('unassign'))}/></>}
 {panel==='snooze'&&<><T size={12} muted>{t("actions.snoozeHint")}</T><View style={{flexDirection:'row',gap:6,flexWrap:'wrap'}}>{[[60,t("actions.oneHour")],[240,t("actions.fourHours")],[-1,t("actions.tomorrow")]].map(([value,label])=>option(String(label),duration===value,()=>setDuration(Number(value))))}</View><Button label={t("actions.confirmSnooze")} disabled={busy||s.offline} onPress={()=>{const until=new Date();if(duration===-1){until.setDate(until.getDate()+1);until.setHours(9,0,0,0)}else until.setTime(Date.now()+duration*60000);void run(()=>s.transition('snooze',{until:until.toISOString()}))}}/></>}
 {panel==='canned'&&<>{create?<><Field label={t("actions.replyName")} testID="canned-name" value={name} onChange={setName}/><Field label={t("actions.replyText")} testID="canned-body" value={body} onChange={setBody} multiline/><Button label={t("actions.saveCanned")} disabled={busy||s.offline||!name.trim()||!body.trim()} onPress={()=>{setBusy(true);void s.repo!.api.request<CannedResponse>({method:'POST',path:'/inbox/api/canned-responses',body:{name,body}}).then(async item=>{const items=[...canned,item];await s.repo!.disk.put('feature:canned',items);setCanned(items);setCreate(false);setName('');setBody('')}).catch(e=>setError(String(e))).finally(()=>setBusy(false))}}/><Button quiet label={t("actions.backCanned")} onPress={()=>setCreate(false)}/></>:<><T size={12} muted>{t("actions.chooseCanned")}</T>{canned.map(item=><Tap key={item.id} label={item.name} testID={'canned-'+item.id} onPress={()=>{s.setDraft(s.draft+(s.draft?'\n':'')+item.body);onClose();s.notify(t("actions.insertedDraft"))}}><Card><T size={12} bold>{item.name}</T><T size={12} muted>{item.body}</T></Card></Tap>)}{!canned.length&&<T muted size={12}>{loading?t("actions.loadingCanned"):s.offline?t("actions.noLocalCanned"):t("actions.noCanned")}</T>}<Button quiet label={t("actions.newCanned")} onPress={()=>setCreate(true)} disabled={s.offline}/></>}</>}
 {panel==='agent'&&<>{conversation.agent&&<Card><T bold size={13}>{conversation.agent.name}</T><T size={12} muted>{conversation.agent.status==='active'?t("actions.attending"):t("actions.paused")} · {t("actions.responseCount",{count:conversation.agent.count})}</T></Card>}<T size={12} muted>{t("actions.aiHint")}</T><Button quiet label={t("actions.takePause")} disabled={busy||s.offline} onPress={()=>void run(()=>s.transition('take'))}/>{agents.map(agent=><Button key={agent.key} quiet testID={'agent-'+agent.key} label={t("actions.routeAgent",{name:agent.name})+(agent.allowed===false?' · '+(agent.reason_label||t("actions.unavailable")):'')} disabled={busy||s.offline||agent.allowed===false} onPress={()=>void run(()=>s.feature('ai',{action:'assign',key:agent.key}))}/>)}{conversation.agent&&<Button quiet label={t("actions.resetAI")} disabled={busy||s.offline} onPress={()=>setConfirm('reset')}/>} {confirm==='reset'&&<Card><T size={12}>{t("actions.resetWarning")}</T><Button label={t("actions.confirmReset")} disabled={busy} onPress={()=>void run(()=>s.feature('ai',{action:'reset'}))}/></Card>}</>}
 {panel==='moderation'&&<>{confirm?<><Card><T size={13}>{warning}</T></Card><Button label={t("actions.confirmModeration")} testID="confirm-moderation" disabled={busy||s.offline} onPress={()=>void run(()=>s.feature('moderation',{action:confirm}))}/><Button quiet label={t("actions.cancelModeration")} onPress={()=>setConfirm('')}/></>:<><T size={12} muted>{t("actions.moderationHint")}</T>{(conversation.moderation?.spam?[['restore',t("actions.restore")]]:[['spam',t("actions.spam")]]).map(([action,label])=><Button key={action} quiet label={label} testID={'moderation-'+action} disabled={s.offline} onPress={()=>setConfirm(action)}/>)}{(s.active?.mode==='mock'||conversation.channel==='instagram')&&<Button quiet label={conversation.moderation?.hidden?(s.active?.mode==='mock'?t("actions.showMock"):t("actions.showInstagram")):(s.active?.mode==='mock'?t("actions.hideMock"):t("actions.hideInstagram"))} testID="moderation-hide" disabled={s.offline} onPress={()=>setConfirm(conversation.moderation?.hidden?'show':'hide')}/>}<Button quiet label={conversation.moderation?.blockedAuthor?t("actions.unblock"):t("actions.block")} testID="moderation-block" disabled={s.offline} onPress={()=>setConfirm(conversation.moderation?.blockedAuthor?'unblock':'block')}/></>}</>}
 {panel==='crm'&&<>{review?<><Card><T bold size={13}>{t("actions.review")}</T><T size={12}>{t("actions.contactLabel",{name:crm.matches?.find(x=>x.id===contactId)?.name||crm.contact?.name||conversation.contact_name})}</T><T size={12}>{address}</T>{campaign&&<T size={12}>{t("actions.campaignLabel",{name:campaign.name})}</T>}{segment&&<T size={12}>{t("actions.segmentLabel",{name:segment.name})}</T>}<T size={11} muted>{s.active?.mode==='mock'?t("actions.crmMockHint"):t("actions.crmHint")}</T></Card>{(crm.matches||[]).filter(x=>x.id!==conversation.contact?.id).map(item=><Button quiet key={item.id} label={t("actions.linkTo",{name:item.name,email:item.email})} onPress={()=>setContactId(item.id)}/>)}<T size={11} muted>{t("actions.selectedLink",{contact:contactId?t("actions.contactId",{id:contactId}):(crm.matches?.length?t("actions.chooseContact"):t("actions.createEmailContact"))})}</T><Button label={t("actions.apply")} disabled={busy||s.offline||crm.can_edit===false||(!contactId&&!!crm.matches?.length)} testID="crm-apply" onPress={()=>void run(()=>s.feature('email-actions',{email:address,contact_id:contactId,save_email:true,campaign_id:campaign?.id||0,segment_id:segment?.id||0}))}/><Button quiet label={t("actions.edit")} onPress={()=>setReview(false)}/></>:<><Field label={t("actions.contactEmail")} testID="crm-email" value={address} onChange={setAddress} keyboardType="email-address"/><CrmAutocomplete kind="campaign" label={t("actions.addCampaign")} value={campaign} onChange={setCampaign} expanded={catalogue==='campaign'} onExpandedChange={open=>setCatalogue(open?'campaign':null)} disabled={busy||crm.can_edit===false}/><CrmAutocomplete kind="segment" label={t("actions.addSegment")} value={segment} onChange={setSegment} expanded={catalogue==='segment'} onExpandedChange={open=>setCatalogue(open?'segment':null)} disabled={busy||crm.can_edit===false}/><Button label={t("actions.review")} disabled={busy||crm.can_edit===false||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(address)||s.offline} onPress={()=>{setCatalogue(null);setBusy(true);setError('');void s.repo!.api.request<any>({method:'GET',path:`/inbox/api/conversations/${s.conversationId}/email-options`,query:{email:address,include_catalog:0}}).then(data=>{setCrm(data);setReview(true)}).catch(e=>setError(String(e))).finally(()=>setBusy(false))}}/></>}</>}
 {error&&<T accessibilityRole="alert" size={12} color={c.warn}>{error}</T>}{busy&&<T size={11} muted>{t("actions.saving")}</T>}
 </Sheet>;
}
