import {t} from '../i18n/engine';
import React,{useEffect,useRef,useState} from 'react';
import {View,TextInput,ScrollView,Keyboard,ActivityIndicator} from 'react-native';
import {useApp} from '../store/app';
import {useTheme,font} from '../theme';
import {T,Tap,Icon} from './ui';
import {loadCataloguePage,type CatalogueKind,type CrmOption} from './crm-catalogue';

export function CrmAutocomplete({kind,label,value,onChange,expanded,onExpandedChange,disabled=false,emptyLabel=t("crm.unchanged")}:{kind:CatalogueKind;label:string;value:CrmOption|null;onChange:(option:CrmOption|null)=>void;expanded:boolean;onExpandedChange:(open:boolean)=>void;disabled?:boolean;emptyLabel?:string}){
 const c=useTheme();const repo=useApp(s=>s.repo);const offline=useApp(s=>s.offline);const account=useApp(s=>s.active?.id);
 const [query,setQuery]=useState('');const [items,setItems]=useState<CrmOption[]>([]);const [cursor,setCursor]=useState<string|null>(null);const [next,setNext]=useState<string|null>(null);const [loading,setLoading]=useState(false);const [error,setError]=useState('');const [retry,setRetry]=useState(0);const generation=useRef(0);const input=useRef<TextInput>(null);
 useEffect(()=>{generation.current++;setQuery('');setCursor(null);setItems([]);setNext(null);setError('')},[account,kind]);
 useEffect(()=>{
  const current=++generation.current;setItems([]);setNext(null);setError('');setLoading(expanded&&!disabled);
  if(!expanded||disabled||!repo)return;
  const timer=setTimeout(()=>{void loadCataloguePage(repo,kind,query,cursor,offline).then(page=>{if(current===generation.current&&useApp.getState().repo===repo){setItems(page.items);setNext(page.next_cursor)}}).catch(e=>{if(current===generation.current)setError(e instanceof Error?e.message:String(e))}).finally(()=>{if(current===generation.current)setLoading(false)})},250);
  return()=>{clearTimeout(timer);generation.current++};
 },[expanded,disabled,repo,kind,query,cursor,offline,retry]);
 function close(){generation.current++;onExpandedChange(false);input.current?.blur();Keyboard.dismiss()}
 function choose(option:CrmOption|null){onChange(option);setCursor(null);close()}
 return <View style={{gap:7}}><T bold size={12}>{label}</T><View style={{minHeight:48,flexDirection:'row',alignItems:'center',borderWidth:1,borderColor:expanded?c.blue:c.line,borderRadius:13,backgroundColor:c.raised,opacity:disabled?.5:1}}><View style={{paddingLeft:12}}><Icon name="search" size={17} color={c.faint}/></View><TextInput ref={input} accessibilityRole="combobox" accessibilityLabel={label} accessibilityState={{expanded,disabled}} testID={'crm-'+kind+'-search'} editable={!disabled} value={expanded?query:value?.name||''} placeholder={expanded?(kind==='campaign'?t("crm.searchCampaign"):t("crm.searchSegment")):emptyLabel} placeholderTextColor={c.soft} autoCorrect={false} autoCapitalize="none" maxLength={100} onFocus={()=>{setQuery('');setCursor(null);onExpandedChange(true)}} onChangeText={text=>{generation.current++;setItems([]);setNext(null);setQuery(text);setCursor(null);onExpandedChange(true)}} style={{flex:1,minWidth:0,minHeight:48,paddingHorizontal:10,paddingVertical:10,fontFamily:font.regular,fontSize:14,color:c.ink,includeFontPadding:false}}/><Tap label={expanded?t("crm.closeSearch"):value?t("crm.clearField",{label:label}):t("crm.searchField",{label:label})} disabled={disabled} testID={'crm-'+kind+'-toggle'} onPress={()=>{if(expanded)close();else if(value)choose(null);else input.current?.focus()}} style={{width:44,alignItems:'center'}}><Icon name={expanded||value?'close':'chevron-down'} size={17} color={c.soft}/></Tap></View>
 {expanded&&!disabled&&<View style={{borderWidth:1,borderColor:c.line,borderRadius:13,backgroundColor:c.paper,overflow:'hidden'}}><Tap label={emptyLabel} testID={'crm-'+kind+'-unchanged'} onPress={()=>choose(null)} style={{paddingHorizontal:12,minHeight:44,borderBottomWidth:1,borderColor:c.line,flexDirection:'row',justifyContent:'space-between'}}><T size={13} color={c.blue}>{emptyLabel}</T>{!value&&<Icon name="checkmark" color={c.blue} size={16}/>}</Tap>{loading?<View accessibilityRole="progressbar" accessibilityLabel={t("crm.searchingOptions")} style={{minHeight:48,paddingHorizontal:12,flexDirection:'row',alignItems:'center',gap:8}}><ActivityIndicator size="small" color={c.blue}/><T muted size={12}>{t("crm.searching")}</T></View>:error?<View style={{padding:12,gap:5}}><T size={12} color={c.warn} accessibilityRole="alert">{error}</T>{!offline&&<Tap label={t("crm.retry")} onPress={()=>setRetry(x=>x+1)}><T color={c.blue} size={12}>{t("crm.retry")}</T></Tap>}</View>:<><ScrollView nestedScrollEnabled keyboardShouldPersistTaps="handled" style={{maxHeight:220}}>{items.map(option=><Tap key={option.id} testID={'crm-'+kind+'-option-'+option.id} label={option.name} onPress={()=>choose(option)} style={{minHeight:44,paddingHorizontal:12,paddingVertical:8,flexDirection:'row',justifyContent:'space-between',gap:8,borderBottomWidth:1,borderColor:c.line}}><T size={13} style={{flex:1,lineHeight:19}}>{option.name}</T>{value?.id===option.id&&<Icon name="checkmark" size={16} color={c.blue}/>}</Tap>)}{!items.length&&<T muted size={12} style={{padding:12}}>{t("crm.empty")}</T>}</ScrollView>{(next||cursor)&&<View style={{flexDirection:'row',borderTopWidth:1,borderColor:c.line}}>{cursor&&<Tap label={t("crm.backFirst")} onPress={()=>setCursor(null)} style={{flex:1,paddingHorizontal:12}}><T color={c.blue} size={12}>{t("crm.firstResults")}</T></Tap>}{next&&<Tap label={t("crm.viewMore")} testID={'crm-'+kind+'-more'} onPress={()=>setCursor(next)} style={{flex:1,paddingHorizontal:12}}><T color={c.blue} size={12}>{t("crm.moreResults")}</T></Tap>}</View>}<T size={11} muted style={{paddingHorizontal:12,paddingVertical:8}}>{offline?t("crm.cachedResults"):t("crm.refineHint")}</T></>}</View>}
 </View>;
}
